name: CI for Flask Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # If you have tests, run them here
        # For example, if you use pytest, you could do:
        # pytest
        echo "No tests defined."

    - name: Lint code
      run: |
        # Optionally, you can add a linter like flake8 or pylint
        # pip install flake8
        # flake8 .
        echo "No linting defined."
